"""Qx devtools: shared code-quality configuration.

Services pin to the same lint/type/format rules by extending the framework
config rather than re-declaring it. The text constants here let a service's
pyproject.toml or pre-commit config compose from a single source of truth.
"""

from __future__ import annotations

from pathlib import Path

__version__ = "0.2.0"

__all__ = [
    "EDITORCONFIG",
    "MYPY_CONFIG",
    "PRE_COMMIT_CONFIG",
    "RUFF_CONFIG",
    "__version__",
    "write_configs",
]


RUFF_CONFIG = """\
# Generated by qx-devtools — pin to framework conventions
line-length = 100
target-version = "py312"

[lint]
select = [
    "E", "W", "F", "I", "B", "C4", "UP", "N", "S", "RUF", "PL", "ASYNC", "PERF",
]
ignore = ["E501", "S101", "PLR0913"]

[lint.per-file-ignores]
"tests/**" = ["S", "PLR2004"]
"alembic/versions/**" = ["F401", "E402"]

[format]
quote-style = "double"
docstring-code-format = true
"""

MYPY_CONFIG = """\
# Generated by qx-devtools
[mypy]
python_version = 3.12
strict = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
warn_unreachable = True
plugins = pydantic.mypy

[mypy-tests.*]
disallow_untyped_defs = False

[mypy-alembic.versions.*]
ignore_errors = True
"""


PRE_COMMIT_CONFIG = """\
# Generated by qx-devtools
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [pydantic, types-PyYAML]
        args: [--strict]
        exclude: ^(tests/|alembic/)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
"""


EDITORCONFIG = """\
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.{py,toml,yaml,yml,json}]
indent_style = space
indent_size = 4
"""


def write_configs(
    target: Path,
    *,
    ruff: bool = True,
    mypy: bool = True,
    pre_commit: bool = True,
    editorconfig: bool = True,
    overwrite: bool = False,
) -> list[Path]:
    """Write the standard config files into a project directory.

    Returns the list of files written. Files that already exist are skipped
    unless ``overwrite=True``.
    """
    target = Path(target)
    target.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    files: list[tuple[str, str]] = []
    if ruff:
        files.append(("ruff.toml", RUFF_CONFIG))
    if mypy:
        files.append(("mypy.ini", MYPY_CONFIG))
    if pre_commit:
        files.append((".pre-commit-config.yaml", PRE_COMMIT_CONFIG))
    if editorconfig:
        files.append((".editorconfig", EDITORCONFIG))

    for name, content in files:
        path = target / name
        if path.exists() and not overwrite:
            continue
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written
