"""Transactional outbox.

The outbox is the textbook pattern for atomic state-change + event-publishing:

1. The application writes the aggregate change and inserts a row into
   ``outbox_events`` in the **same SQL transaction**. Either both succeed or
   both roll back.
2. A separate ``OutboxRelay`` worker polls the table, publishes pending rows
   to the message broker (NATS JetStream), and marks them as published.

This module supplies:

- The ``outbox_events`` Table definition (services include it in their
  metadata via ``include_outbox_table(metadata)``).
- The ``OutboxRecorder`` which serializes ``IntegrationEvent`` instances and
  inserts them in the UoW's transaction.
- The relay worker itself lives in ``qx-events`` — it depends on a
  broker, and we keep the database package broker-agnostic.

Schema choice: store the full event envelope as JSONB plus a few denormalized
columns we'll want to query/index (event_name, occurred_at, tenant_id). This
lets you do `SELECT * FROM outbox_events WHERE event_name = 'user.registered'
AND published_at IS NULL` without parsing JSON.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, Protocol, runtime_checkable
from uuid import uuid4

from sqlalchemy import (
    Column,
    DateTime,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

if TYPE_CHECKING:
    from collections.abc import Sequence

    from qx.core import IntegrationEvent
    from sqlalchemy.ext.asyncio import AsyncSession

__all__ = [
    "OUTBOX_TABLE_NAME",
    "DefaultOutboxRecorder",
    "OutboxRecorder",
    "include_outbox_table",
]


OUTBOX_TABLE_NAME = "qx_outbox_events"


def include_outbox_table(metadata: MetaData) -> Table:
    """Register the outbox table in the given metadata.

    Services call this once during their mapping setup so Alembic picks up the
    table in autogenerated revisions.
    """
    return Table(
        OUTBOX_TABLE_NAME,
        metadata,
        Column("id", PG_UUID(as_uuid=True), primary_key=True),
        Column("event_name", String(255), nullable=False),
        Column("event_version", Integer, nullable=False, default=1),
        Column("payload", JSONB, nullable=False),
        Column("occurred_at", DateTime(timezone=True), nullable=False),
        Column("correlation_id", PG_UUID(as_uuid=True), nullable=True),
        Column("causation_id", PG_UUID(as_uuid=True), nullable=True),
        Column("tenant_id", PG_UUID(as_uuid=True), nullable=True),
        Column("published_at", DateTime(timezone=True), nullable=True),
        Column("attempts", Integer, nullable=False, default=0),
        Column("last_error", String(2048), nullable=True),
        Index(f"ix_{OUTBOX_TABLE_NAME}_pending", "published_at", "occurred_at"),
        Index(f"ix_{OUTBOX_TABLE_NAME}_event_name", "event_name"),
    )


@runtime_checkable
class OutboxRecorder(Protocol):
    """Protocol the UoW uses to write integration events to the outbox.

    Kept abstract so test cases and alternative storage (e.g., outbox-as-Kafka-
    log for very high throughput) can swap in.
    """

    async def record(
        self,
        session: AsyncSession,
        events: Sequence[IntegrationEvent],
    ) -> None: ...


class DefaultOutboxRecorder:
    """Inserts rows into the PostgreSQL outbox table inside the current transaction."""

    def __init__(self, table_name: str = OUTBOX_TABLE_NAME) -> None:
        self._table = table_name

    async def record(
        self,
        session: AsyncSession,
        events: Sequence[IntegrationEvent],
    ) -> None:
        if not events:
            return
        rows = [
            {
                "id": str(uuid4()),
                "event_name": ev.event_name,
                "event_version": ev.event_version,
                "payload": json.dumps(ev.envelope()),
                "occurred_at": ev.occurred_at,
                "correlation_id": str(ev.correlation_id) if ev.correlation_id else None,
                "causation_id": str(ev.causation_id) if ev.causation_id else None,
                "tenant_id": str(ev.tenant_id) if ev.tenant_id else None,
                "published_at": None,
                "attempts": 0,
                "last_error": None,
            }
            for ev in events
        ]
        # We use an inline INSERT to keep this module free of a Table dep on
        # the live MetaData (the service owns the metadata; we just write).
        await session.execute(
            text(
                f"""
                INSERT INTO {self._table}
                    (id, event_name, event_version, payload, occurred_at,
                     correlation_id, causation_id, tenant_id, published_at,
                     attempts, last_error)
                VALUES
                    (:id, :event_name, :event_version, CAST(:payload AS JSONB),
                     :occurred_at, :correlation_id, :causation_id, :tenant_id,
                     :published_at, :attempts, :last_error)
                """
            ),
            rows,
        )
