"""Dead Letter Queue — persist and re-route exhausted messages.

When a NATS JetStream message reaches its ``max_deliver`` limit without a
successful ack, the worker routes it here instead of naking indefinitely:

1. Write a row to ``qx_dead_letters`` (Postgres) with the full envelope,
   NATS headers, delivery count, and the last error string.
2. Publish a compact notification to ``qx_dlq.<event_name>`` on NATS so
   monitoring and alert rules can react without polling the DB.

The worker then acks the original message so it is removed from the JetStream
consumer's pending set — NATS would stop redelivering at this point anyway.

Replay is performed via ``qx dlq replay <id>`` (the CLI command), which reads
the row, reconstructs the original payload, and re-publishes it to the
message's original NATS subject.
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any
from uuid import uuid4

from sqlalchemy import Column, DateTime, Integer, MetaData, String, Table, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

if TYPE_CHECKING:
    from qx.db.engine import SessionFactory

__all__ = [
    "DLQ_SUBJECT_PREFIX",
    "DLQ_TABLE_NAME",
    "DeadLetterStore",
    "include_dead_letters_table",
]

DLQ_TABLE_NAME = "qx_dead_letters"
DLQ_SUBJECT_PREFIX = "qx_dlq"

_log = logging.getLogger("qx.worker.dlq")


def include_dead_letters_table(metadata: MetaData) -> Table:
    """Register ``qx_dead_letters`` in the given SQLAlchemy metadata.

    Services call this alongside ``include_outbox_table`` so Alembic picks up
    the table in autogenerated revisions.
    """
    return Table(
        DLQ_TABLE_NAME,
        metadata,
        Column("id", PG_UUID(as_uuid=True), primary_key=True),
        Column("event_name", String(255), nullable=False),
        Column("event_version", Integer, nullable=False, server_default="1"),
        Column("payload", JSONB, nullable=False),
        Column("headers", JSONB, nullable=True),
        Column("subject", String(512), nullable=False),
        Column("correlation_id", PG_UUID(as_uuid=True), nullable=True),
        Column("tenant_id", PG_UUID(as_uuid=True), nullable=True),
        Column("delivered_count", Integer, nullable=False, server_default="1"),
        Column("last_error", String(2048), nullable=True),
        Column("failed_at", DateTime(timezone=True), nullable=False),
    )


class DeadLetterStore:
    """Persist exhausted messages and publish a DLQ notification.

    Args:
        session_factory: SQLAlchemy ``async_sessionmaker`` — called once per
            ``persist()`` invocation to open a short-lived session.
        js: NATS ``JetStreamContext`` for side-channel publish.  May be
            ``None``; the DB write still proceeds, the NATS publish is skipped.
        subject_prefix: NATS subject prefix for DLQ notifications.
            Default: ``"qx_dlq"``.

    Usage::

        dlq = DeadLetterStore(
            session_factory=make_session_factory(engine),
            js=nats_client.jetstream(),
        )
        runtime = WorkerRuntime(..., dlq=dlq)
    """

    def __init__(
        self,
        session_factory: SessionFactory,
        js: Any | None = None,
        *,
        subject_prefix: str = DLQ_SUBJECT_PREFIX,
    ) -> None:
        self._factory = session_factory
        self._js = js
        self._prefix = subject_prefix

    async def persist(self, msg: Any, *, error: str | None = None) -> None:
        """Persist *msg* to ``qx_dead_letters`` and publish a DLQ notification.

        Failures during the DB write are re-raised so the caller can log them
        and still ack the original message (NATS would stop redelivering
        anyway).  Failures during the NATS publish are suppressed — the row is
        the authoritative record.
        """
        row_id = uuid4()
        event_name = (msg.headers or {}).get("qx.event_name", "<unknown>")
        event_version = int((msg.headers or {}).get("qx.event_version", 1))

        try:
            envelope = json.loads(msg.data.decode())
        except Exception:
            envelope = {"raw": msg.data.hex() if msg.data else ""}

        delivered_count = _num_delivered(msg)
        correlation_id = (msg.headers or {}).get("qx.correlation_id")
        tenant_id = (msg.headers or {}).get("qx.tenant_id")
        subject = getattr(msg, "subject", None) or ""
        headers_dict = dict(msg.headers or {})
        now = datetime.now(UTC)

        async with self._factory() as session:
            await session.execute(
                text(
                    f"""
                    INSERT INTO {DLQ_TABLE_NAME}
                        (id, event_name, event_version, payload, headers,
                         subject, correlation_id, tenant_id,
                         delivered_count, last_error, failed_at)
                    VALUES
                        (:id, :event_name, :event_version,
                         CAST(:payload AS JSONB), CAST(:headers AS JSONB),
                         :subject, :correlation_id, :tenant_id,
                         :delivered_count, :last_error, :failed_at)
                    """
                ),
                {
                    "id": str(row_id),
                    "event_name": event_name,
                    "event_version": event_version,
                    "payload": json.dumps(envelope),
                    "headers": json.dumps(headers_dict),
                    "subject": subject,
                    "correlation_id": correlation_id,
                    "tenant_id": tenant_id,
                    "delivered_count": delivered_count,
                    "last_error": (error or "")[:2048],
                    "failed_at": now,
                },
            )
            await session.commit()

        _log.warning(
            "message moved to DLQ",
            extra={
                "dlq_id": str(row_id),
                "event_name": event_name,
                "delivered_count": delivered_count,
                "error": error,
            },
        )

        if self._js is not None:
            await _publish_notification(
                self._js,
                subject_prefix=self._prefix,
                event_name=event_name,
                row_id=str(row_id),
                subject=subject,
                error=error,
                failed_at=now,
            )


def _num_delivered(msg: Any) -> int:
    """Extract ``num_delivered`` from NATS JetStream message metadata."""
    meta = getattr(msg, "metadata", None)
    if meta is None:
        return 1
    val = getattr(meta, "num_delivered", None)
    return int(val) if val is not None else 1


async def _publish_notification(
    js: Any,
    *,
    subject_prefix: str,
    event_name: str,
    row_id: str,
    subject: str,
    error: str | None,
    failed_at: datetime,
) -> None:
    try:
        notification = json.dumps(
            {
                "id": row_id,
                "event_name": event_name,
                "subject": subject,
                "failed_at": failed_at.isoformat(),
                "last_error": error,
            }
        ).encode()
        await js.publish(f"{subject_prefix}.{event_name}", notification)
    except Exception:
        _log.debug("DLQ NATS notification failed (non-fatal)", exc_info=True)
